### PR TITLE
Add more space themes to chapter 4.

### PR DESCRIPTION
**Pull request by gilfoyleismyothername**
I made some great space themed changes to your original storyline! (Which was a great storyline btw!)

### CODE REVIEW

**Review by angelabauer — APPROVED** [review]
Great job Gilfoyle!

**Comment by hamza-essam** [comment]
I made some great space themed changes

**Comment by hamza-essam** [comment]
> I made some great space themed changes

**Comment by PortalWalkerCodes** [comment]
Bro this has 1 merged PR. THERE IS 300 LOL

**Pull request merged**
